# Generated by Django 4.1 on 2023-02-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0011_alter_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                ("active", models.BooleanField()),
                (
                    "products",
                    models.ManyToManyField(blank=True, to="products.product"),
                ),
            ],
        ),
    ]
