# Generated by Django 3.1 on 2021-06-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_auto_20210625_1801"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products"
            ),
        ),
    ]
