# Generated by Django 3.1 on 2021-06-25 15:27

from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_auto_20210625_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=products.models.upload_image_path,
            ),
        ),
    ]
