# Generated by Django 3.1 on 2021-06-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_auto_20210625_1827"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
